use_frameworks!
platform :ios, '11.0'
pod 'BarcodeScanner' #, path: '../../'
pod 'FlagPhoneNumber'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'SVProgressHUD'
target 'Refundis'
